services:
  postgres-db:
    ports:
      - "5432:5432"
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: chatApp
      POSTGRES_PASSWORD: passwordChat
      POSTGRES_DB: aiDb
  ollama:
    hostname: ollama
    container_name: ollama
    image: ollama/ollama
    ports:
      - "11434:11434"

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 3000:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always

volumes:
  ollama: {}
  open-webui: {}