version: '3.9'

services:
  postgres-db:
    ports:
      - "5432:5432"
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: chatApp
      POSTGRES_PASSWORD: passwordChat
      POSTGRES_DB: aiDb